# A subset of NSE tickers for the dropdown. 
# In a real production app, this might come from a database or an API endpoint that updates daily.
NSE_TICKERS = [
    {"label": "Reliance Industries", "value": "RELIANCE.NS"},
    {"label": "Tata Consultancy Services", "value": "TCS.NS"},
    {"label": "HDFC Bank", "value": "HDFCBANK.NS"},
    {"label": "Infosys", "value": "INFY.NS"},
    {"label": "ICICI Bank", "value": "ICICIBANK.NS"},
    {"label": "Hindustan Unilever", "value": "HINDUNILVR.NS"},
    {"label": "Bharti Airtel", "value": "BHARTIARTL.NS"},
    {"label": "Bajaj Finance", "value": "BAJFINANCE.NS"},
    {"label": "Kotak Mahindra Bank", "value": "KOTAKBANK.NS"},
    {"label": "Wipro", "value": "WIPRO.NS"},
    {"label": "HCL Technologies", "value": "HCLTECH.NS"},
    {"label": "Asian Paints", "value": "ASIANPAINT.NS"},
    {"label": "ITC", "value": "ITC.NS"},
    {"label": "Larsen & Toubro", "value": "LT.NS"},
    {"label": "Maruti Suzuki", "value": "MARUTI.NS"},
    {"label": "Sun Pharmaceutical", "value": "SUNPHARMA.NS"},
    {"label": "Titan Company", "value": "TITAN.NS"},
    {"label": "Axis Bank", "value": "AXISBANK.NS"},
    {"label": "Ultratech Cement", "value": "ULTRACEMCO.NS"},
    {"label": "Nestle India", "value": "NESTLEIND.NS"},
    {"label": "Tata Steel", "value": "TATASTEEL.NS"},
    {"label": "NTPC", "value": "NTPC.NS"},
    {"label": "Power Grid Corporation", "value": "POWERGRID.NS"},
    {"label": "Mahindra & Mahindra", "value": "M&M.NS"},
    {"label": "Tata Motors", "value": "TATAMOTORS.NS"},
    {"label": "Adani Enterprises", "value": "ADANIENT.NS"},
    {"label": "Adani Ports", "value": "ADANIPORTS.NS"},
    {"label": "Bajaj Finserv", "value": "BAJAJFINSV.NS"},
    {"label": "Coal India", "value": "COALINDIA.NS"},
    {"label": "JSW Steel", "value": "JSWSTEEL.NS"},
    {"label": "State Bank of India", "value": "SBIN.NS"},
    {"label": "Grasim Industries", "value": "GRASIM.NS"},
    {"label": "Cipla", "value": "CIPLA.NS"},
    {"label": "Tech Mahindra", "value": "TECHM.NS"},
    {"label": "Hindalco Industries", "value": "HINDALCO.NS"},
    {"label": "Divi's Laboratories", "value": "DIVISLAB.NS"},
    {"label": "Dr. Reddy's Laboratories", "value": "DRREDDY.NS"},
    {"label": "Eicher Motors", "value": "EICHERMOT.NS"},
    {"label": "SBI Life Insurance", "value": "SBILIFE.NS"},
    {"label": "HDFC Life Insurance", "value": "HDFCLIFE.NS"},
    {"label": "Britannia Industries", "value": "BRITANNIA.NS"},
    {"label": "Apollo Hospitals", "value": "APOLLOHOSP.NS"},
    {"label": "Hero MotoCorp", "value": "HEROMOTOCO.NS"},
    {"label": "IndusInd Bank", "value": "INDUSINDBK.NS"},
    {"label": "Oil & Natural Gas Corporation", "value": "ONGC.NS"},
    {"label": "Tata Consumer Products", "value": "TATACONSUM.NS"},
    {"label": "UPL", "value": "UPL.NS"},
    {"label": "Bharat Petroleum", "value": "BPCL.NS"},
    {"label": "Zomato", "value": "ZOMATO.NS"},
    {"label": "Paytm", "value": "PAYTM.NS"},
    {"label": "Nykaa", "value": "NYKAA.NS"},
     {"label": "Adani Green Energy", "value": "ADANIGREEN.NS"}
]
